<?php
/**
 * AuthErrorCode
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * OpenAPI spec version: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RuncloudIO\SDK\OPENFGA\Model;
use \RuncloudIO\SDK\OPENFGA\ObjectSerializer;

/**
 * AuthErrorCode Class Doc Comment
 *
 * Required Attributes:
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 *
class AuthErrorCode
{
    /**
     * Possible values of this enum
     */
    const NO_AUTH_ERROR = 'no_auth_error';
    const AUTH_FAILED_INVALID_SUBJECT = 'auth_failed_invalid_subject';
    const AUTH_FAILED_INVALID_AUDIENCE = 'auth_failed_invalid_audience';
    const AUTH_FAILED_INVALID_ISSUER = 'auth_failed_invalid_issuer';
    const INVALID_CLAIMS = 'invalid_claims';
    const AUTH_FAILED_INVALID_BEARER_TOKEN = 'auth_failed_invalid_bearer_token';
    const BEARER_TOKEN_MISSING = 'bearer_token_missing';
    const UNAUTHENTICATED = 'unauthenticated';
    const FORBIDDEN = 'forbidden';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            test
            self::NO_AUTH_ERROR
            test
            self::AUTH_FAILED_INVALID_SUBJECT
            test
            self::AUTH_FAILED_INVALID_AUDIENCE
            test
            self::AUTH_FAILED_INVALID_ISSUER
            test
            self::INVALID_CLAIMS
            test
            self::AUTH_FAILED_INVALID_BEARER_TOKEN
            test
            self::BEARER_TOKEN_MISSING
            test
            self::UNAUTHENTICATED
            test
            self::FORBIDDEN
        ];
    }
}
