<?php
/**
 * ErrorCode
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * OpenAPI spec version: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RuncloudIO\SDK\OPENFGA\Model;
use \RuncloudIO\SDK\OPENFGA\ObjectSerializer;

/**
 * ErrorCode Class Doc Comment
 *
 * Required Attributes:
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 *
class ErrorCode
{
    /**
     * Possible values of this enum
     */
    const NO_ERROR = 'no_error';
    const VALIDATION_ERROR = 'validation_error';
    const AUTHORIZATION_MODEL_NOT_FOUND = 'authorization_model_not_found';
    const AUTHORIZATION_MODEL_RESOLUTION_TOO_COMPLEX = 'authorization_model_resolution_too_complex';
    const INVALID_WRITE_INPUT = 'invalid_write_input';
    const CANNOT_ALLOW_DUPLICATE_TUPLES_IN_ONE_REQUEST = 'cannot_allow_duplicate_tuples_in_one_request';
    const CANNOT_ALLOW_DUPLICATE_TYPES_IN_ONE_REQUEST = 'cannot_allow_duplicate_types_in_one_request';
    const CANNOT_ALLOW_MULTIPLE_REFERENCES_TO_ONE_RELATION = 'cannot_allow_multiple_references_to_one_relation';
    const INVALID_CONTINUATION_TOKEN = 'invalid_continuation_token';
    const INVALID_TUPLE_SET = 'invalid_tuple_set';
    const INVALID_CHECK_INPUT = 'invalid_check_input';
    const INVALID_EXPAND_INPUT = 'invalid_expand_input';
    const UNSUPPORTED_USER_SET = 'unsupported_user_set';
    const INVALID_OBJECT_FORMAT = 'invalid_object_format';
    const WRITE_FAILED_DUE_TO_INVALID_INPUT = 'write_failed_due_to_invalid_input';
    const AUTHORIZATION_MODEL_ASSERTIONS_NOT_FOUND = 'authorization_model_assertions_not_found';
    const LATEST_AUTHORIZATION_MODEL_NOT_FOUND = 'latest_authorization_model_not_found';
    const TYPE_NOT_FOUND = 'type_not_found';
    const RELATION_NOT_FOUND = 'relation_not_found';
    const EMPTY_RELATION_DEFINITION = 'empty_relation_definition';
    const INVALID_USER = 'invalid_user';
    const INVALID_TUPLE = 'invalid_tuple';
    const UNKNOWN_RELATION = 'unknown_relation';
    const STORE_ID_INVALID_LENGTH = 'store_id_invalid_length';
    const ASSERTIONS_TOO_MANY_ITEMS = 'assertions_too_many_items';
    const ID_TOO_LONG = 'id_too_long';
    const AUTHORIZATION_MODEL_ID_TOO_LONG = 'authorization_model_id_too_long';
    const TUPLE_KEY_VALUE_NOT_SPECIFIED = 'tuple_key_value_not_specified';
    const TUPLE_KEYS_TOO_MANY_OR_TOO_FEW_ITEMS = 'tuple_keys_too_many_or_too_few_items';
    const PAGE_SIZE_INVALID = 'page_size_invalid';
    const PARAM_MISSING_VALUE = 'param_missing_value';
    const DIFFERENCE_BASE_MISSING_VALUE = 'difference_base_missing_value';
    const SUBTRACT_BASE_MISSING_VALUE = 'subtract_base_missing_value';
    const OBJECT_TOO_LONG = 'object_too_long';
    const RELATION_TOO_LONG = 'relation_too_long';
    const TYPE_DEFINITIONS_TOO_FEW_ITEMS = 'type_definitions_too_few_items';
    const TYPE_INVALID_LENGTH = 'type_invalid_length';
    const TYPE_INVALID_PATTERN = 'type_invalid_pattern';
    const RELATIONS_TOO_FEW_ITEMS = 'relations_too_few_items';
    const RELATIONS_TOO_LONG = 'relations_too_long';
    const RELATIONS_INVALID_PATTERN = 'relations_invalid_pattern';
    const OBJECT_INVALID_PATTERN = 'object_invalid_pattern';
    const QUERY_STRING_TYPE_CONTINUATION_TOKEN_MISMATCH = 'query_string_type_continuation_token_mismatch';
    const EXCEEDED_ENTITY_LIMIT = 'exceeded_entity_limit';
    const INVALID_CONTEXTUAL_TUPLE = 'invalid_contextual_tuple';
    const DUPLICATE_CONTEXTUAL_TUPLE = 'duplicate_contextual_tuple';
    const INVALID_AUTHORIZATION_MODEL = 'invalid_authorization_model';
    const UNSUPPORTED_SCHEMA_VERSION = 'unsupported_schema_version';
    const CANCELLED = 'cancelled';
    const INVALID_START_TIME = 'invalid_start_time';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            test
            self::NO_ERROR
            test
            self::VALIDATION_ERROR
            test
            self::AUTHORIZATION_MODEL_NOT_FOUND
            test
            self::AUTHORIZATION_MODEL_RESOLUTION_TOO_COMPLEX
            test
            self::INVALID_WRITE_INPUT
            test
            self::CANNOT_ALLOW_DUPLICATE_TUPLES_IN_ONE_REQUEST
            test
            self::CANNOT_ALLOW_DUPLICATE_TYPES_IN_ONE_REQUEST
            test
            self::CANNOT_ALLOW_MULTIPLE_REFERENCES_TO_ONE_RELATION
            test
            self::INVALID_CONTINUATION_TOKEN
            test
            self::INVALID_TUPLE_SET
            test
            self::INVALID_CHECK_INPUT
            test
            self::INVALID_EXPAND_INPUT
            test
            self::UNSUPPORTED_USER_SET
            test
            self::INVALID_OBJECT_FORMAT
            test
            self::WRITE_FAILED_DUE_TO_INVALID_INPUT
            test
            self::AUTHORIZATION_MODEL_ASSERTIONS_NOT_FOUND
            test
            self::LATEST_AUTHORIZATION_MODEL_NOT_FOUND
            test
            self::TYPE_NOT_FOUND
            test
            self::RELATION_NOT_FOUND
            test
            self::EMPTY_RELATION_DEFINITION
            test
            self::INVALID_USER
            test
            self::INVALID_TUPLE
            test
            self::UNKNOWN_RELATION
            test
            self::STORE_ID_INVALID_LENGTH
            test
            self::ASSERTIONS_TOO_MANY_ITEMS
            test
            self::ID_TOO_LONG
            test
            self::AUTHORIZATION_MODEL_ID_TOO_LONG
            test
            self::TUPLE_KEY_VALUE_NOT_SPECIFIED
            test
            self::TUPLE_KEYS_TOO_MANY_OR_TOO_FEW_ITEMS
            test
            self::PAGE_SIZE_INVALID
            test
            self::PARAM_MISSING_VALUE
            test
            self::DIFFERENCE_BASE_MISSING_VALUE
            test
            self::SUBTRACT_BASE_MISSING_VALUE
            test
            self::OBJECT_TOO_LONG
            test
            self::RELATION_TOO_LONG
            test
            self::TYPE_DEFINITIONS_TOO_FEW_ITEMS
            test
            self::TYPE_INVALID_LENGTH
            test
            self::TYPE_INVALID_PATTERN
            test
            self::RELATIONS_TOO_FEW_ITEMS
            test
            self::RELATIONS_TOO_LONG
            test
            self::RELATIONS_INVALID_PATTERN
            test
            self::OBJECT_INVALID_PATTERN
            test
            self::QUERY_STRING_TYPE_CONTINUATION_TOKEN_MISMATCH
            test
            self::EXCEEDED_ENTITY_LIMIT
            test
            self::INVALID_CONTEXTUAL_TUPLE
            test
            self::DUPLICATE_CONTEXTUAL_TUPLE
            test
            self::INVALID_AUTHORIZATION_MODEL
            test
            self::UNSUPPORTED_SCHEMA_VERSION
            test
            self::CANCELLED
            test
            self::INVALID_START_TIME
        ];
    }
}
