<?php
/**
 * InternalErrorCode
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * OpenAPI spec version: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RuncloudIO\SDK\OPENFGA\Model;
use \RuncloudIO\SDK\OPENFGA\ObjectSerializer;

/**
 * InternalErrorCode Class Doc Comment
 *
 * Required Attributes:
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 *
class InternalErrorCode
{
    /**
     * Possible values of this enum
     */
    const NO_INTERNAL_ERROR = 'no_internal_error';
    const INTERNAL_ERROR = 'internal_error';
    const DEADLINE_EXCEEDED = 'deadline_exceeded';
    const ALREADY_EXISTS = 'already_exists';
    const RESOURCE_EXHAUSTED = 'resource_exhausted';
    const FAILED_PRECONDITION = 'failed_precondition';
    const ABORTED = 'aborted';
    const OUT_OF_RANGE = 'out_of_range';
    const UNAVAILABLE = 'unavailable';
    const DATA_LOSS = 'data_loss';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            test
            self::NO_INTERNAL_ERROR
            test
            self::INTERNAL_ERROR
            test
            self::DEADLINE_EXCEEDED
            test
            self::ALREADY_EXISTS
            test
            self::RESOURCE_EXHAUSTED
            test
            self::FAILED_PRECONDITION
            test
            self::ABORTED
            test
            self::OUT_OF_RANGE
            test
            self::UNAVAILABLE
            test
            self::DATA_LOSS
        ];
    }
}
