<?php
/**
 * StoreIdWriteBody
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * OpenAPI spec version: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RuncloudIO\SDK\OPENFGA\Model;

use \RuncloudIO\SDK\OPENFGA\ObjectSerializer;

/**
 * StoreIdWriteBody Class Doc Comment
 *
 * Required Attributes:
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 *
 *
 * @method \RuncloudIO\SDK\OPENFGA\Model\WriteRequestWrites getWrites()
 * @method $this setWrites($writes)
 * @method \RuncloudIO\SDK\OPENFGA\Model\WriteRequestDeletes getDeletes()
 * @method $this setDeletes($deletes)
 * @method string getAuthorizationModelId()
 * @method $this setAuthorizationModelId($authorization_model_id)
 *
 */
class StoreIdWriteBody implements ModelInterface
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'store_id_write_body';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'writes' => '\RuncloudIO\SDK\OPENFGA\Model\WriteRequestWrites',
        'deletes' => '\RuncloudIO\SDK\OPENFGA\Model\WriteRequestDeletes',
        'authorization_model_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'writes' => null,
        'deletes' => null,
        'authorization_model_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'writes' => 'writes',
        'deletes' => 'deletes',
        'authorization_model_id' => 'authorization_model_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'writes' => 'setWrites',
        'deletes' => 'setDeletes',
        'authorization_model_id' => 'setAuthorizationModelId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'writes' => 'getWrites',
        'deletes' => 'getDeletes',
        'authorization_model_id' => 'getAuthorizationModelId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param \RuncloudIO\SDK\OPENFGA\Model\WriteRequestWrites $writes writes 
     * @param \RuncloudIO\SDK\OPENFGA\Model\WriteRequestDeletes $deletes deletes 
     * @param string $authorization_model_id authorization_model_id 
     *   Associated array of property values initializing the model
     */
    public function __construct(\RuncloudIO\SDK\OPENFGA\Model\WriteRequestWrites $writes, \RuncloudIO\SDK\OPENFGA\Model\WriteRequestDeletes $deletes, string $authorization_model_id)
    {
        if(!is_null($writes)) {
            $this->container['writes'] = $writes;
        }
        if(!is_null($deletes)) {
            $this->container['deletes'] = $deletes;
        }
        if(!is_null($authorization_model_id)) {
            $this->container['authorization_model_id'] = $authorization_model_id;
        }
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets writes
     *
     * @return \RuncloudIO\SDK\OPENFGA\Model\WriteRequestWrites
     */
    public function getWrites()
    {
        return $this->container['writes'];
    }

    /**
     * Sets writes
     *
     * @param \RuncloudIO\SDK\OPENFGA\Model\WriteRequestWrites $writes writes
     *
     * @return $this
     */
    public function setWrites($writes)
    {
        $this->container['writes'] = $writes;

        return $this;
    }

    /**
     * Gets deletes
     *
     * @return \RuncloudIO\SDK\OPENFGA\Model\WriteRequestDeletes
     */
    public function getDeletes()
    {
        return $this->container['deletes'];
    }

    /**
     * Sets deletes
     *
     * @param \RuncloudIO\SDK\OPENFGA\Model\WriteRequestDeletes $deletes deletes
     *
     * @return $this
     */
    public function setDeletes($deletes)
    {
        $this->container['deletes'] = $deletes;

        return $this;
    }

    /**
     * Gets authorization_model_id
     *
     * @return string
     */
    public function getAuthorizationModelId()
    {
        return $this->container['authorization_model_id'];
    }

    /**
     * Sets authorization_model_id
     *
     * @param string $authorization_model_id authorization_model_id
     *
     * @return $this
     */
    public function setAuthorizationModelId($authorization_model_id)
    {
        $this->container['authorization_model_id'] = $authorization_model_id;

        return $this;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
