<?php
/**
 * TypeName
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * OpenAPI spec version: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RuncloudIO\SDK\OPENFGA\Model;
use \RuncloudIO\SDK\OPENFGA\ObjectSerializer;

/**
 * TypeName Class Doc Comment
 *
 * Required Attributes:
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 *
class TypeName
{
    /**
     * Possible values of this enum
     */
    const UNSPECIFIED = 'TYPE_NAME_UNSPECIFIED';
    const ANY = 'TYPE_NAME_ANY';
    const BOOL = 'TYPE_NAME_BOOL';
    const STRING = 'TYPE_NAME_STRING';
    const INT = 'TYPE_NAME_INT';
    const UINT = 'TYPE_NAME_UINT';
    const DOUBLE = 'TYPE_NAME_DOUBLE';
    const DURATION = 'TYPE_NAME_DURATION';
    const TIMESTAMP = 'TYPE_NAME_TIMESTAMP';
    const MAP = 'TYPE_NAME_MAP';
    const _LIST = 'TYPE_NAME_LIST';
    const IPADDRESS = 'TYPE_NAME_IPADDRESS';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            test
            self::UNSPECIFIED
            test
            self::ANY
            test
            self::BOOL
            test
            self::STRING
            test
            self::INT
            test
            self::UINT
            test
            self::DOUBLE
            test
            self::DURATION
            test
            self::TIMESTAMP
            test
            self::MAP
            test
            self::_LIST
            test
            self::IPADDRESS
        ];
    }
}
