<?php
/**
 * UnprocessableContentErrorCode
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * OpenAPI spec version: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RuncloudIO\SDK\OPENFGA\Model;
use \RuncloudIO\SDK\OPENFGA\ObjectSerializer;

/**
 * UnprocessableContentErrorCode Class Doc Comment
 *
 * Required Attributes:
 *
 * @category Class
 * @package  RuncloudIO\SDK\OPENFGA
 * @author   Runcloud Engineering Team
 * @link     https://github.com/swagger-api/swagger-codegen
 *
class UnprocessableContentErrorCode
{
    /**
     * Possible values of this enum
     */
    const NO_THROTTLED_ERROR_CODE = 'no_throttled_error_code';
    const THROTTLED_TIMEOUT_ERROR = 'throttled_timeout_error';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            test
            self::NO_THROTTLED_ERROR_CODE
            test
            self::THROTTLED_TIMEOUT_ERROR
        ];
    }
}
